language: python

python:
    - "2.7"

install:
    - pip install flake8
    - pip install -r requirements.txt

notifications:
    email:
        - geowatch.dev@gmail.com

before_script:
    flake8 geowatchutil

script: python -m unittest geowatchutil.tests.test
